version: "3.8"

services:
  # photo-studio-back:
  #   image: photo-studio-back-image
  #   container_name: photo-studio-back-cont
  #   restart: always
  #   ports: 
  #     - "5050:80"
  jenkins:
    image: jenkin-final
    container_name: jenkins
    privileged: true
    ports: 
      - "8080:8080"
      - "50000:50000"    
    volumes: 
     - jenkins_home:/var/jenkins_home
     - //var/run/docker.sock:/var/run/docker.sock
  mongo:
    container_name: mongo_graylog
    image: mongo:4.2
  elasticsearch:
    container_name: elasticserach_graylog
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
  graylog:
    image: graylog/graylog:4.0
    environment:
      # at least 16 characters
      - GRAYLOG_PASSWORD_SECRET=thispassshouldbeatleast16characters
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      - 9000:9000 # Graylog web interface and REST API
      - 1514:1514
      - 1514:1514/udp
      - 12201:12201
      - 12201:12201/udp
  #############################
  # Graylog configuration end #
  #############################
    
volumes: 
  jenkins_home:
    external: true